name: Build library

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
        id: checkout
        uses: actions/checkout@v2
      - name: Set up JDK 8
        id: setup_env
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Set gradlew permissions
        id: set_gradle_perms
        run: chmod u+x gradlew
        # why not
      - name: Validate Gradle wrapper
        id: validate_gradle
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Publish package
        id: publish
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: publish --no-daemon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
