name: Build, publish release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'release version') || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: "temurin"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew publishMavenPublicationToBartoszsRepoReleasesRepository -PbartoszsRepoReleasesUsername=${{ secrets.MAVEN_RELEASES_NAME }} -PbartoszsRepoReleasesPassword=${{ secrets.MAVEN_RELEASES_SECRET }}