name: Build, publish release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'release version') }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: "temurin"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build publishMavenPublicationToBartoszsRepoReleasesRepository
        env:
          MAVEN_NAME: ${{ secrets.MANEN_RELEASES_NAME }}
          MAVEN_SECRET: ${{ secrets.MANEN_RELEASES_SECRET }}